### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by SirCraftypants** [OmegaWeaponDev/Stylizer#5]
Paper Spigot 1.16.5 #570
Minecraft Client
Java 11

I'm getting this Error upon update to Stylizer 2.0.9 from 2.0.6.

https://paste.helpch.at/wazepowogo.md

reverting back to 2.0.6 for now.

**Comment by OmegaWeaponDev** [comment]
Hi SirCraftyPants,

I have had a look at the error, and the only issue seems to be that you have a simple syntax error in the config.yml which is resulting in the null error. Please copy and paste your full config.yml to http://yaml-online-parser.appspot.com/ and see if you're able to resolve the issue. If not, simply upload your config.yml to one of the paste services and send me the link and I'll take a look at it for you.

**Comment by SirCraftypants** [comment]
Ok i've figured out what i needed to do, i deleted the Stylizer plugin folder completely and installed the updated 2.0.9 and it's working. 

It seems like update 2.0.8+ doesn't like my config on 2.0.6

**Comment by OmegaWeaponDev** [comment]
That should not be an issue as there was only just a syntax error. You simply just needed to find where the syntax error was and fix it then it would work. As I have a config auto updater implemented so you'll always receive the latest updates to the config files if there are any. 

The error you sent clearly starts it was a syntax error. Which is pretty common, all you needed to do was fix where the syntax was wrong and reload the plugin.

**Comment by SirCraftypants** [comment]
> 
> 
> That should not be an issue as there was only just a syntax error. You simply just needed to find where the syntax error was and fix it then it would work. As I have a config auto updater implemented so you'll always receive the latest updates to the config files if there are any.
> 
> The error you sent clearly starts it was a syntax error. Which is pretty common, all you needed to do was fix where the syntax was wrong and reload the plugin.

Easier for me to just delete and have it regenerate, instead of looking for it. Either way problem solved.
