### ISSUE TITLE
Library-1.6.2 not compiling correctly from Maven Import (Eclipse)

### ISSUE THREAD

**Issue by ChipmunkCraft** [OmegaWeaponDev/Stylizer#6]
When I imported an "Existing Maven Project;" it appears that library-1.6.2.jar was not compiled properly.

The image below shows the only 2 files listed (Which I found out are not "jar" files the hard way, lol).  All the other dependencies compiled and imported just fine.
I tried deleting and re-importing the whole project 2 times with the same results.

Is there another way to obtain this jar file?  (Not familiar with how Maven grabs these libraries and compiles them)

My assumption is I either did something wrong on importing or what Maven needs to compile this library doesn't exist anymore?
If a compiled version of library-1.6.2.jar can simply be downloaded and put in the folder; that solution works for me.  I would just need to know where to obtain it.

![image](https://user-images.githubusercontent.com/11890508/115641946-e8585d80-a2ce-11eb-96a5-397211395cd2.png)

**Comment by OmegaWeaponDev** [comment]
Why are you trying to import Stylizer?

**Comment by ChipmunkCraft** [comment]
There are features and parts I don't need and looking to downsize the Plugin.  Not to release but for my own private use on my computer.

**Comment by OmegaWeaponDev** [comment]
You can disable the features that you're not wanting to use in the config.yml. The library that I use is a private library that my friend and I use which we don't give out to people.

**Comment by ChipmunkCraft** [comment]
I see.  So this is not an Open Source project?  Didn't see a license or anything.  I'll delete the source code on my computer then,

**Comment by OmegaWeaponDev** [comment]
If there are features you're not wanting to use, just disable them in the config.yml. That's why I have implemented an option to disable them.

**Comment by NotAlexNoyle** [comment]
> I see. So this is not an Open Source project? Didn't see a license or anything. I'll delete the source code on my computer then,

Correct. Warning to all who use this, it uses a proprietary library and the .jars are not reproducible. I asked the developer for the source code to the library multiple times over almost a year, and they don't seem to care. The GPLv3 tag is deceptive.
