### ISSUE TITLE
Problem when i install the plugin

### ISSUE THREAD

**Issue by Nobilesama** [OmegaWeaponDev/Stylizer#7]
hello. After installing the plugin, when I start the server it tells me that the plugin was loaded but then it gives an error as in the screenshot and the plugin is deactivated. My server is in 1.17.1 and the plugin version is v2.0.28
![Captura de pantalla 2021-11-06 193312](https://user-images.githubusercontent.com/93844840/140625656-7a36e7f0-4a05-4c7f-9655-c7a0f4afb8c0.png)

**Comment by OmegaWeaponDev** [comment]
Hi,

Please make sure you have Vault installed on the server as well. Many of the Stylizer features rely heavily on Vault for them to work correctly.

Thanks,
OmegaWeaponDev

**Comment by Nobilesama** [comment]
Yes, I have it and it doesn't work

**Comment by OmegaWeaponDev** [comment]
Okay, I'll have a look into it a little later today when I have some time. 

Thanks

**Comment by OmegaWeaponDev** [comment]
Hi @Nobilesama,

Please download and install the latest version 2.0.29 from spigot and let me know if it resolves the issue.

Thanks,
OmegaWeaponDev

**Comment by Nobilesama** [comment]
Hi
I install it and it doesn't work

**Comment by OmegaWeaponDev** [comment]
Is it the same error as before or a different one?

**Comment by OmegaWeaponDev** [comment]
Hmm alright. Are you using paper, spigot or craft Bukkit, which version of it, and what vault version. Could you also show me a screenshot of your plugins folder.

**Comment by Nobilesama** [comment]
I deleted the information of the discord to which it is connected for privacy reasons
[console.txt](https://github.com/OmegaWeaponDev/Stylizer/files/7498736/console.txt)

**Comment by OmegaWeaponDev** [comment]
Please use a paste service like hastebin.com or similar. As it is much easier to view than a text file.

**Comment by OmegaWeaponDev** [comment]
Hi @Nobilesama 

Please try this version. I've tested it and it works fine for me. If it does not work again, please try updating your paper version to the latest and make sure you remove any old versions of Stylizer.

[Stylizer-2.0.30.zip](https://github.com/OmegaWeaponDev/Stylizer/files/7502086/Stylizer-2.0.30.zip)

**Comment by Nobilesama** [comment]
I have tried both things and it keeps giving error. I send you
 capture again in case something changed.
![Captura de pantalla 2021-11-09 220510](https://user-images.githubusercontent.com/93844840/141030899-8ea98d69-de12-47d1-8d0a-5cca721230a0.png)

**Comment by OmegaWeaponDev** [comment]
Hi,

I have just done some testing and messed around with a couple things and I also had another look at the console log you sent above, I believe the issue may be coming from your plugin PowerRanks.

I have tested it with PowerRanks and tested with other plugins like Luckperms and GroupManager and found it works with others but always breaks with PowerRanks. So this is not something I can fix as it's PowerRanks not using Vault correctly. 

I'd advise you move to a more robust and properly built plugin like Luckperms.

Thanks.

**Comment by Nobilesama** [comment]
Ok, thank you. I'm going to see it
